### ISSUE TITLE
1.19.4遇到的问题

### ISSUE THREAD

**Issue by kaka2022** [ColdeZhang/LiveBot#2]
您好，我是paper1.19.4，目前遇到的问题，切换人物时，可能会有卡到虚空的问题，切换世界的话，这个现象就比在一个世界切换还要严重，跟随人物时，有的时候会原地不动，然后再跟上去，或者是说跟随的人已经走了，他还在原地，挂机检测也有一点小问题，如果您哪天有时间，还请您更新一下插件，麻烦您了

**Comment by ColdeZhang** [comment]
你好 感谢你的使用与反馈
这个属于插件早期的设计问题。
由于这个插件是我刚上手做的头几个插件之一，那个时候我对游戏的运行时机制一知半解，因此导致了此插件逻辑设计上的不合理。最近在忙于小创世神插件的开发，所以这个插件的优化会在之后一段时间实施。
预本插件预计会在六月底发布一个2.0版本以解决这些问题。

#1

**Comment by kaka2022** [comment]
> 
感谢回复，期待您的更新！

**Comment by ColdeZhang** [comment]
你好 😄
刚刚已经更新了2.0预览版，欢迎尝试。 @wkurumi @kaka2022 
目前应该大概率解决了上述问题（不排除偶发性的卡虚空），如果有问题麻烦在此回复告知。
下载地址：[https://github.com/ColdeZhang/LiveBot/releases](https://github.com/ColdeZhang/LiveBot/releases)

**Comment by kaka2022** [comment]
> 你好 😄 刚刚已经更新了2.0预览版，欢迎尝试。 @wkurumi @kaka2022 目前应该大概率解决了上述问题（不排除偶发性的卡虚空），如果有问题麻烦在此回复告知。 下载地址：https://github.com/ColdeZhang/LiveBot/releases

[09:21:00 INFO]: ceshi issued server command: /livebot status
[09:21:00 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'livebot' in plugin LiveBot v2.2-snapshot
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.4.jar:git-Paper-545]
        at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-545]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2257) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-545]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-545]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "deercloud.livebot.PlayerCache.getCurrentFollowingPlayerName()" because "this.m_player_cache" is null
        at deercloud.livebot.Commands.printStatus(Commands.java:140) ~[LiveBot-2.2-snapshot.jar:?]
        at deercloud.livebot.Commands.onCommand(Commands.java:126) ~[LiveBot-2.2-snapshot.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by ColdeZhang** [comment]
> > 你好 😄 刚刚已经更新了2.0预览版，欢迎尝试。 @wkurumi @kaka2022 目前应该大概率解决了上述问题（不排除偶发性的卡虚空），如果有问题麻烦在此回复告知。 下载地址：https://github.com/ColdeZhang/LiveBot/releases
> 
> [09:21:00 INFO]: ceshi issued server command: /livebot status [09:21:00 ERROR]: null org.bukkit.command.CommandException: Unhandled exception executing command 'livebot' in plugin LiveBot v2.2-snapshot at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?] at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.4.jar:git-Paper-545] at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-545] at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?] at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?] at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2297) ~[?:?] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2257) ~[?:?] at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?] at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-545] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-545] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-545] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-545] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-545] at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1428) ~[paper-1.19.4.jar:git-Paper-545] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1174) ~[paper-1.19.4.jar:git-Paper-545] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-545] at java.lang.Thread.run(Thread.java:833) ~[?:?] Caused by: java.lang.NullPointerException: Cannot invoke "deercloud.livebot.PlayerCache.getCurrentFollowingPlayerName()" because "this.m_player_cache" is null at deercloud.livebot.Commands.printStatus(Commands.java:140) ~[LiveBot-2.2-snapshot.jar:?] at deercloud.livebot.Commands.onCommand(Commands.java:126) ~[LiveBot-2.2-snapshot.jar:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?] ... 23 more

已针对高版本进行了一些修改 请前往release下载2.7尝试一下

**Comment by kaka2022** [comment]
> > > 你好 😄 刚刚已经更新了2.0预览版，欢迎尝试。 @wkurumi @kaka2022 目前应该大概率解决了上述问题（不排除偶发性的卡虚空），如果有问题麻烦在此回复告知。 下载地址：https://github.com/ColdeZhang/LiveBot/releases
> > 
> > 
> > [09：21：00 信息]： ceshi 发出的服务器命令： /livebot status [09：21：00 错误]： null org.bukkit.command.CommandException： 在插件 LiveBot v2.2-snapshot at org.bukkit.command.PluginCommand.execute（PluginCommand.java：47） ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar：？] at org.bukkit.command.SimpleCommandMap.dispatch（SimpleCommandMap.java：155） ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar：？] at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand（CraftServer.java：909） ~[paper-1.19.4.jar：git-Paper-545] at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run（BukkitCommandWrapper.java：64） ~[paper-1.19.4.jar：git-Paper-545] at com.mojang.brigadier.CommandDispatcher.execute（CommandDispatcher.java：264） ~[paper-1.19.4.jar：？] at net.minecraft.command.Commands.performCommand（Commands.java：322） ~[？：？] at net.minecraft.command.Command.Command.performCommand（Commands.java：306） ~[?:?]at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand（ServerGamePacketListenerImpl.java：2297） ~[？：？] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20（ServerGamePacketListenerImpl.java：2257） ~[？：？] at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0（BlockableEventLoop.java：59） ~[？：？] at java.util.concurrent.CompletableFuture$AsyncSupply.run（CompletableFuture.java：1768） ~[？：？]at net.minecraft.server.TickTask.run（TickTask.java：18） ~[paper-1.19.4.jar：git-Paper-545] at net.minecraft.util.thread.BlockableEventLoop.doRunTask（BlockableEventLoop.java：153） ~[？：？] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask（ReentrantBlockableEventLoop.java：24） ~[？：？] at net.minecraft.server.MinecraftServer.doRunTask（MinecraftServer.java：1342） ~[paper-1.19.4.jar：git-Paper-545] at net.minecraft.server.MinecraftServer.d（MinecraftServer.java：197） ~[paper-1.19.4.jar：git-Paper-545] at net.minecraft.util.thread.BlockableEventLoop.pollTask（BlockableEventLoop.java：126） ~[？：？] at net.minecraft.server.MinecraftServer.pollTaskInternal（MinecraftServer.java：1319） ~[paper-1.19.4.jar：git-Paper-545] at net.minecraft.server.MinecraftServer.pollTask（MinecraftServer.java：1312） ~[paper-1.19.4.jar：git-Paper-545] at net.minecraft.util.thread.BlockableEventLoop.runAllTasks（BlockableEventLoop.java：114） ~[？：？] at net.minecraft.server.MinecraftServer.tickServer（MinecraftServer.java：1428） ~[paper-1.19.4.jar：git-Paper-545] at net.minecraft.server.MinecraftServer.runServer（MinecraftServer.java：1174） ~[paper-1.19.4.jar：git-Paper-545] at net.minecraft.server.MinecraftServer.lambda$spin$0（MinecraftServer.java：320） ~[paper-1.19.4.jar：git-Paper-545] at java.lang.Thread.run（Thread.java：833） ~[？：？]由： java.lang.NullPointerException： 无法调用 “deercloud.livebot.PlayerCache.getCurrentFollowPlayerName（）” 因为 “this.m_player_cache” 在 deercloud.livebot.Command.printStatus（Commands.java：140） ~[LiveBot-2.2-snapshot.jar：？] at deercloud.livebot.Command.onCommand（Commands.java：126） ~[LiveBot-2.2-snapshot.jar：？] at org.bukkit.command.PluginCommand.execute（PluginCommand.java：45） ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar：？] ...还有 23 个
> 
> 已针对高版本进行了一些修改 请前往release下载2.7尝试一下

非常感谢，已测试一周，目前1.19.4非常好用，切换时间和检测挂机时间，非常准确，谢谢

**Comment by ColdeZhang** [comment]
挂机检测时间的配置已经去除了 可以把那个删掉
现在是自适应检测

**Comment by ColdeZhang** [comment]
ps 最近做了个新的插件 生存用的小创世神 有兴趣的话可以试一试 可以用来平地之类的 @kaka2022 
[LiteWorldEdit](https://github.com/ColdeZhang/LiteWorldEdit)

**Comment by kaka2022** [comment]
> ps 最近做了个新的插件 生存用的小创世神 有兴趣的话可以试一试 可以用来平地之类的 [LiteWorldEdit](https://github.com/ColdeZhang/LiteWorldEdit)

ok，我用一下，生存用的话，因为有许多建筑玩家，要是能加一下限制，比如付费，时间限制等最好了，目前来看，很好用！
